import { CertificateTemplate } from '../../../../shared/types/learning-engine.js';

export const REUSABLE_CERTIFICATE_TEMPLATES: CertificateTemplate[] = [
  {
    id: 'tmpl_cert_course',
    certificateTypeCode: 'COURSE_COMPLETION',
    title: 'Certificate of Course Completion',
    description: 'Awarded to employees or students upon successful completion of structured curricula and coursework.',
    headerText: 'TASKNERA ENTERPRISE ACADEMY',
    subHeaderText: 'CERTIFICATE OF COMPLETION',
    bodyTemplate:
      'This is proudly presented to {{recipientName}} in recognition of successfully completing the prescribed coursework and fulfilling all curriculum criteria for {{courseTitle}} with distinction.',
    signatoryName: 'Sakshi Koparde',
    signatoryTitle: 'Head of Learning & People Development',
    secondarySignatoryName: 'Alex Vance',
    secondarySignatoryTitle: 'Chief Technology Officer',
    badgeTitle: 'VERIFIED COURSEWORK',
    styleTheme: 'ROYAL_BLUE',
  },
  {
    id: 'tmpl_cert_training',
    certificateTypeCode: 'TRAINING_CERTIFICATE',
    title: 'Certificate of Professional Training',
    description: 'Awarded for advanced vocational, compliance, or technical training bootcamps.',
    headerText: 'TASKNERA LEARNING & TALENT DEVELOPMENT',
    subHeaderText: 'PROFESSIONAL TRAINING ACCREDITATION',
    bodyTemplate:
      'This certifies that {{recipientName}} from {{recipientDepartment}} has completed comprehensive professional training in {{courseTitle}}, demonstrating excellence in practical execution.',
    signatoryName: 'Sakshi Koparde',
    signatoryTitle: 'VP of People Operations',
    secondarySignatoryName: 'Rajesh Sharma',
    secondarySignatoryTitle: 'Principal Training Officer',
    badgeTitle: 'ACCREDITED TRAINING',
    styleTheme: 'EMERALD_GOLD',
  },
  {
    id: 'tmpl_cert_internship',
    certificateTypeCode: 'INTERNSHIP_CERTIFICATE',
    title: 'Certificate of Internship Completion',
    description: 'Formal attestation of tenure, project deliverables, and successful conclusion of internship.',
    headerText: 'TASKNERA ENTERPRISE CORP',
    subHeaderText: 'CERTIFICATE OF INTERNSHIP',
    bodyTemplate:
      'This certificate is presented to {{recipientName}} for successfully completing an intensive software engineering internship in {{recipientDepartment}}. During this tenure, the candidate demonstrated diligence, technical acumen, and exceptional collaboration on {{courseTitle}}.',
    signatoryName: 'Sakshi Koparde',
    signatoryTitle: 'Senior HR Operations Partner',
    secondarySignatoryName: 'David Kim',
    secondarySignatoryTitle: 'Engineering Mentor & Lead',
    badgeTitle: 'INTERNSHIP HONORS',
    styleTheme: 'CLASSIC_SLATE',
  },
  {
    id: 'tmpl_cert_participation',
    certificateTypeCode: 'PARTICIPATION_CERTIFICATE',
    title: 'Certificate of Active Participation',
    description: 'Recognizes active attendance and contribution in corporate hackathons, seminars, or summits.',
    headerText: 'TASKNERA ANNUAL WORKFORCE SUMMIT',
    subHeaderText: 'CERTIFICATE OF PARTICIPATION',
    bodyTemplate:
      'Awarded to {{recipientName}} for active and valuable participation in {{courseTitle}}, contributing to our culture of continuous learning and innovation.',
    signatoryName: 'Sakshi Koparde',
    signatoryTitle: 'Director of Employee Experience',
    badgeTitle: 'PARTICIPANT',
    styleTheme: 'CORPORATE_PURPLE',
  },
  {
    id: 'tmpl_cert_achievement',
    certificateTypeCode: 'ACHIEVEMENT_CERTIFICATE',
    title: 'Certificate of Exceptional Achievement',
    description: 'Conferred for top performance percentiles, hackathon victories, or benchmark project delivery.',
    headerText: 'TASKNERA ENTERPRISE EXCELLENCE AWARDS',
    subHeaderText: 'CERTIFICATE OF ACHIEVEMENT',
    bodyTemplate:
      'In tribute to exemplary dedication and remarkable results, this Certificate of Achievement is bestowed upon {{recipientName}} for outstanding milestones attained in {{courseTitle}}.',
    signatoryName: 'Alex Vance',
    signatoryTitle: 'Chief Technology Officer',
    secondarySignatoryName: 'Sakshi Koparde',
    secondarySignatoryTitle: 'VP of People & Culture',
    badgeTitle: 'TOP ACHIEVER',
    styleTheme: 'EMERALD_GOLD',
  },
  {
    id: 'tmpl_cert_appreciation',
    certificateTypeCode: 'APPRECIATION_CERTIFICATE',
    title: 'Certificate of Appreciation & Leadership',
    description: 'Formal company acknowledgment of extraordinary mentorship, culture leadership, or voluntary service.',
    headerText: 'TASKNERA EXECUTIVE LEADERSHIP COUNCIL',
    subHeaderText: 'CERTIFICATE OF APPRECIATION',
    bodyTemplate:
      'With sincere gratitude and high regard, TaskNera recognizes {{recipientName}} for distinguished service, dedication, and steadfast support during {{courseTitle}}.',
    signatoryName: 'Sakshi Koparde',
    signatoryTitle: 'Chief People Officer',
    badgeTitle: 'HONORARY RECOGNITION',
    styleTheme: 'ROYAL_BLUE',
  },
];
