// =============================================================================
// STEP 10: PRE-SEEDED QUESTION BANK CATALOG
// =============================================================================

import { AssessmentQuestion } from '../../../../shared/types/assessment-engine.js';

export const DEFAULT_QUESTION_BANK: AssessmentQuestion[] = [
  // 1. Numerical Reasoning
  {
    id: 'qst_num_01',
    category: 'NUMERICAL_REASONING',
    type: 'MULTIPLE_CHOICE',
    difficulty: 'EASY',
    questionText: 'A project team finished 45 out of 60 planned sprint story points. What percentage of the sprint was delivered?',
    options: [
      { id: 'opt_1', text: '70%' },
      { id: 'opt_2', text: '75%' },
      { id: 'opt_3', text: '80%' },
      { id: 'opt_4', text: '85%' },
    ],
    correctOptionIds: ['opt_2'],
    explanation: '45 / 60 = 0.75, which equals 75%.',
    status: 'PUBLISHED',
    isAiGenerated: false,
    reviewedBy: 'usr_admin_001',
    reviewedAt: '2026-09-01T10:00:00Z',
    createdAt: '2026-09-01T10:00:00Z',
    updatedAt: '2026-09-01T10:00:00Z',
  },
  {
    id: 'qst_num_02',
    category: 'NUMERICAL_REASONING',
    type: 'MULTIPLE_CHOICE',
    difficulty: 'MEDIUM',
    questionText:
      'A server cluster costs $1,200/month. By migrating to reserved instances with auto-scaling, monthly costs drop by 35%. What is the annual cost after migration?',
    options: [
      { id: 'opt_1', text: '$7,800' },
      { id: 'opt_2', text: '$9,360' },
      { id: 'opt_3', text: '$8,640' },
      { id: 'opt_4', text: '$10,200' },
    ],
    correctOptionIds: ['opt_2'],
    explanation: 'New monthly cost = $1,200 * (1 - 0.35) = $780. Annual cost = $780 * 12 = $9,360.',
    status: 'PUBLISHED',
    isAiGenerated: false,
    reviewedBy: 'usr_admin_001',
    reviewedAt: '2026-09-01T10:00:00Z',
    createdAt: '2026-09-01T10:00:00Z',
    updatedAt: '2026-09-01T10:00:00Z',
  },

  // 2. Logical Reasoning
  {
    id: 'qst_log_01',
    category: 'LOGICAL_REASONING',
    type: 'MULTIPLE_CHOICE',
    difficulty: 'EASY',
    questionText: 'Identify the next number in the sequence: 3, 7, 15, 31, 63, ?',
    options: [
      { id: 'opt_1', text: '95' },
      { id: 'opt_2', text: '127' },
      { id: 'opt_3', text: '128' },
      { id: 'opt_4', text: '125' },
    ],
    correctOptionIds: ['opt_2'],
    explanation: 'Each term is generated by (previous * 2) + 1. (63 * 2) + 1 = 126 + 1 = 127.',
    status: 'PUBLISHED',
    isAiGenerated: false,
    reviewedBy: 'usr_admin_001',
    reviewedAt: '2026-09-01T10:00:00Z',
    createdAt: '2026-09-01T10:00:00Z',
    updatedAt: '2026-09-01T10:00:00Z',
  },
  {
    id: 'qst_log_02',
    category: 'LOGICAL_REASONING',
    type: 'TRUE_FALSE',
    difficulty: 'MEDIUM',
    questionText:
      'Premise 1: All production deployments require an approved change request. Premise 2: Patch #402 is running in production. Conclusion: Patch #402 had an approved change request.',
    options: [
      { id: 'opt_t', text: 'True (Logically Follows)' },
      { id: 'opt_f', text: 'False (Does Not Follow)' },
    ],
    correctOptionIds: ['opt_t'],
    explanation: 'Deductive modus ponens: since all production deployments require approval and #402 is deployed, it must have had approval.',
    status: 'PUBLISHED',
    isAiGenerated: false,
    reviewedBy: 'usr_admin_001',
    reviewedAt: '2026-09-01T10:00:00Z',
    createdAt: '2026-09-01T10:00:00Z',
    updatedAt: '2026-09-01T10:00:00Z',
  },

  // 3. Verbal Reasoning
  {
    id: 'qst_vrb_01',
    category: 'VERBAL_REASONING',
    type: 'MULTIPLE_CHOICE',
    difficulty: 'MEDIUM',
    questionText:
      'Choose the word that is most nearly opposite in meaning (Antonym) to "Ephemeral":',
    options: [
      { id: 'opt_1', text: 'Transient' },
      { id: 'opt_2', text: 'Enduring' },
      { id: 'opt_3', text: 'Volatile' },
      { id: 'opt_4', text: 'Tentative' },
    ],
    correctOptionIds: ['opt_2'],
    explanation: 'Ephemeral means lasting for a very short time. Its antonym is Enduring (lasting for a long time).',
    status: 'PUBLISHED',
    isAiGenerated: false,
    reviewedBy: 'usr_admin_001',
    reviewedAt: '2026-09-01T10:00:00Z',
    createdAt: '2026-09-01T10:00:00Z',
    updatedAt: '2026-09-01T10:00:00Z',
  },

  // 4. Basic Technical Questions
  {
    id: 'qst_tch_01',
    category: 'BASIC_TECHNICAL',
    type: 'MULTIPLE_CHOICE',
    difficulty: 'EASY',
    questionText: 'Which HTTP status code signifies that the server successfully fulfilled a request and created a new resource?',
    options: [
      { id: 'opt_1', text: '200 OK' },
      { id: 'opt_2', text: '201 Created' },
      { id: 'opt_3', text: '204 No Content' },
      { id: 'opt_4', text: '304 Not Modified' },
    ],
    correctOptionIds: ['opt_2'],
    explanation: 'HTTP 201 Created indicates that the request succeeded and led to the creation of a resource.',
    status: 'PUBLISHED',
    isAiGenerated: false,
    reviewedBy: 'usr_admin_001',
    reviewedAt: '2026-09-01T10:00:00Z',
    createdAt: '2026-09-01T10:00:00Z',
    updatedAt: '2026-09-01T10:00:00Z',
  },
  {
    id: 'qst_tch_02',
    category: 'BASIC_TECHNICAL',
    type: 'MULTIPLE_ANSWERS',
    difficulty: 'MEDIUM',
    questionText: 'Select ALL properties that form the ACID model in transactional relational databases:',
    options: [
      { id: 'opt_a', text: 'Atomicity' },
      { id: 'opt_b', text: 'Consistency' },
      { id: 'opt_c', text: 'Isolation' },
      { id: 'opt_d', text: 'Durability' },
      { id: 'opt_e', text: 'Availability' },
    ],
    correctOptionIds: ['opt_a', 'opt_b', 'opt_c', 'opt_d'],
    explanation: 'ACID stands for Atomicity, Consistency, Isolation, and Durability (Availability is from the CAP theorem).',
    status: 'PUBLISHED',
    isAiGenerated: false,
    reviewedBy: 'usr_admin_001',
    reviewedAt: '2026-09-01T10:00:00Z',
    createdAt: '2026-09-01T10:00:00Z',
    updatedAt: '2026-09-01T10:00:00Z',
  },
];
