import { OnboardingFormConfig } from '../../../../shared/types/onboarding-engine.js';

export const DEFAULT_ONBOARDING_CONFIG: OnboardingFormConfig = {
  id: 'cfg_default_onboarding_v1',
  companyId: 'cmp_tasknera_001',
  version: '1.0',
  title: 'TaskNera Standard Employee Onboarding & Verification',
  description:
    'Comprehensive digital onboarding workflow for newly hired employees covering identity verification, statutory details, and joining checklist.',
  sections: [
    {
      key: 'personal_info',
      title: 'Personal Information',
      description: 'Primary identity and demographic information as recorded in government records.',
      order: 1,
      isEnabled: true,
      isRequired: true,
      fields: [
        {
          key: 'firstName',
          label: 'First Name',
          type: 'TEXT',
          required: true,
          placeholder: 'e.g. Sakshi',
        },
        {
          key: 'middleName',
          label: 'Middle Name',
          type: 'TEXT',
          required: false,
          placeholder: 'Optional',
        },
        {
          key: 'lastName',
          label: 'Last Name',
          type: 'TEXT',
          required: true,
          placeholder: 'e.g. Koparde',
        },
        {
          key: 'dateOfBirth',
          label: 'Date of Birth',
          type: 'DATE',
          required: true,
          helpText: 'Must match government identity document',
        },
        {
          key: 'gender',
          label: 'Gender',
          type: 'SELECT',
          required: true,
          options: ['Female', 'Male', 'Non-Binary', 'Prefer not to say'],
        },
        {
          key: 'bloodGroup',
          label: 'Blood Group',
          type: 'SELECT',
          required: true,
          options: ['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-'],
        },
        {
          key: 'maritalStatus',
          label: 'Marital Status',
          type: 'SELECT',
          required: false,
          options: ['Single', 'Married', 'Divorced', 'Widowed'],
        },
        {
          key: 'nationality',
          label: 'Nationality',
          type: 'TEXT',
          required: true,
          defaultValue: 'Indian',
        },
        {
          key: 'fatherOrSpouseName',
          label: 'Father or Spouse Full Name',
          type: 'TEXT',
          required: false,
          placeholder: 'For statutory documentation',
        },
      ],
    },
    {
      key: 'contact_info',
      title: 'Contact Information',
      description: 'Official communication coordinates and residential addresses.',
      order: 2,
      isEnabled: true,
      isRequired: true,
      fields: [
        {
          key: 'personalEmail',
          label: 'Personal Email',
          type: 'EMAIL',
          required: true,
          placeholder: 'candidate@example.com',
        },
        {
          key: 'mobileNumber',
          label: 'Primary Mobile Number',
          type: 'PHONE',
          required: true,
          placeholder: '+91 98765 43210',
        },
        {
          key: 'alternateNumber',
          label: 'Alternate Phone Number',
          type: 'PHONE',
          required: false,
          placeholder: 'Optional',
        },
        {
          key: 'currentAddress',
          label: 'Current Residential Address',
          type: 'TEXTAREA',
          required: true,
          placeholder: 'Flat/House No, Building, Street, Area',
        },
        {
          key: 'permanentAddress',
          label: 'Permanent Address',
          type: 'TEXTAREA',
          required: true,
          placeholder: 'Same as current or ancestral address',
        },
        {
          key: 'city',
          label: 'City',
          type: 'TEXT',
          required: true,
          placeholder: 'e.g. Pune',
        },
        {
          key: 'state',
          label: 'State / Province',
          type: 'TEXT',
          required: true,
          placeholder: 'e.g. Maharashtra',
        },
        {
          key: 'postalCode',
          label: 'PIN / Postal Code',
          type: 'TEXT',
          required: true,
          placeholder: 'e.g. 411057',
        },
        {
          key: 'country',
          label: 'Country',
          type: 'TEXT',
          required: true,
          defaultValue: 'India',
        },
      ],
    },
    {
      key: 'education',
      title: 'Educational Qualifications',
      description: 'Chronological record of completed diplomas, undergraduate, and postgraduate degrees.',
      order: 3,
      isEnabled: true,
      isRequired: true,
      fields: [
        {
          key: 'records',
          label: 'Education Records',
          type: 'ARRAY',
          required: true,
          helpText: 'Add all completed degrees starting with highest qualification',
        },
      ],
    },
    {
      key: 'previous_employment',
      title: 'Previous Work History',
      description: 'Prior professional employment, designatory titles, and separation rationale.',
      order: 4,
      isEnabled: true,
      isRequired: false, // Optional for freshers
      fields: [
        {
          key: 'records',
          label: 'Employment Records',
          type: 'ARRAY',
          required: false,
          helpText: 'Applicable for lateral and experienced hires',
        },
      ],
    },
    {
      key: 'emergency_contact',
      title: 'Emergency Contact Person',
      description: 'Authorized point of contact in case of workplace emergencies or critical incidents.',
      order: 5,
      isEnabled: true,
      isRequired: true,
      fields: [
        {
          key: 'primaryName',
          label: 'Contact Person Full Name',
          type: 'TEXT',
          required: true,
          placeholder: 'e.g. Rajesh Koparde',
        },
        {
          key: 'relationship',
          label: 'Relationship to Candidate',
          type: 'SELECT',
          required: true,
          options: ['Spouse', 'Parent', 'Sibling', 'Guardian', 'Friend', 'Other'],
        },
        {
          key: 'primaryPhone',
          label: 'Emergency Mobile Phone',
          type: 'PHONE',
          required: true,
          placeholder: '+91 98765 00000',
        },
        {
          key: 'alternatePhone',
          label: 'Alternate Emergency Number',
          type: 'PHONE',
          required: false,
        },
        {
          key: 'address',
          label: 'Emergency Contact Address',
          type: 'TEXTAREA',
          required: false,
        },
      ],
    },
    {
      key: 'bank_details',
      title: 'Bank & Statutory Details',
      description: 'Disbursement bank coordinates for monthly payroll, statutory PF/ESI, and taxation.',
      order: 6,
      isEnabled: true,
      isRequired: true,
      fields: [
        {
          key: 'accountHolderName',
          label: 'Account Holder Name (as in bank)',
          type: 'TEXT',
          required: true,
          placeholder: 'e.g. SAKSHI KOPARDE',
        },
        {
          key: 'bankName',
          label: 'Bank Name',
          type: 'TEXT',
          required: true,
          placeholder: 'e.g. HDFC Bank, ICICI Bank',
        },
        {
          key: 'accountNumber',
          label: 'Bank Account Number',
          type: 'TEXT',
          required: true,
          placeholder: 'Enter bank account number',
        },
        {
          key: 'ifscOrRoutingCode',
          label: 'IFSC Code / Branch Routing',
          type: 'TEXT',
          required: true,
          placeholder: 'e.g. HDFC0001234',
        },
        {
          key: 'branchName',
          label: 'Branch Location',
          type: 'TEXT',
          required: true,
          placeholder: 'e.g. Hinjewadi Phase 1, Pune',
        },
        {
          key: 'accountType',
          label: 'Account Type',
          type: 'SELECT',
          required: true,
          options: ['SAVINGS', 'CURRENT', 'CHECKING'],
        },
        {
          key: 'panNumber',
          label: 'Permanent Account Number (PAN)',
          type: 'TEXT',
          required: true,
          placeholder: 'e.g. ABCDE1234F',
          helpText: 'Mandatory for TDS and salary tax deduction',
        },
      ],
    },
    {
      key: 'document_collection',
      title: 'Document Collection & Verification',
      description: 'Upload certified digital copies of government identification, diplomas, and proof of address.',
      order: 7,
      isEnabled: true,
      isRequired: true,
      fields: [],
    },
    {
      key: 'declaration',
      title: 'Candidate Declaration & Consent',
      description: 'Binding affirmation of truthfulness, background verification consent, and electronic sign-off.',
      order: 8,
      isEnabled: true,
      isRequired: true,
      fields: [
        {
          key: 'hasConsentedBgv',
          label: 'I hereby authorize TaskNera to conduct background verification (education, employment, criminal records).',
          type: 'CHECKBOX',
          required: true,
        },
        {
          key: 'hasConfirmedAccuracy',
          label: 'I certify that all details, certificates, and submissions are accurate, authentic, and complete.',
          type: 'CHECKBOX',
          required: true,
        },
        {
          key: 'agreedToPolicies',
          label: 'I have reviewed and agree to abide by TaskNera Enterprise Policies, Code of Conduct, and IT Guidelines.',
          type: 'CHECKBOX',
          required: true,
        },
        {
          key: 'electronicSignature',
          label: 'Full Legal Name (Electronic Signature)',
          type: 'TEXT',
          required: true,
          placeholder: 'Type your full legal name to sign',
        },
        {
          key: 'signatureDate',
          label: 'Date of Execution',
          type: 'DATE',
          required: true,
        },
      ],
    },
  ],
  requiredDocuments: [
    {
      code: 'PAN_CARD',
      name: 'PAN Card Copy',
      description: 'Government issued Permanent Account Number card',
      required: true,
      acceptedFormats: ['.pdf', '.jpg', '.jpeg', '.png'],
      maxSizeMb: 5,
    },
    {
      code: 'AADHAAR_OR_PASSPORT',
      name: 'Aadhaar / Passport / Government ID',
      description: 'Valid national photo identity proof with address',
      required: true,
      acceptedFormats: ['.pdf', '.jpg', '.jpeg', '.png'],
      maxSizeMb: 5,
    },
    {
      code: 'DEGREE_CERTIFICATE',
      name: 'Highest Educational Degree Certificate',
      description: 'Convocation certificate or final graduation marksheet',
      required: true,
      acceptedFormats: ['.pdf', '.jpg', '.jpeg', '.png'],
      maxSizeMb: 10,
    },
    {
      code: 'RELIEVING_LETTER',
      name: 'Relieving / Experience Letter from Last Employer',
      description: 'Official clearance or experience certificate (if applicable)',
      required: false,
      acceptedFormats: ['.pdf', '.jpg', '.jpeg', '.png'],
      maxSizeMb: 10,
    },
    {
      code: 'PAYSLIPS',
      name: 'Last 3 Months Payslips',
      description: 'Recent salary compensation statements from prior company',
      required: false,
      acceptedFormats: ['.pdf'],
      maxSizeMb: 10,
    },
    {
      code: 'PHOTO',
      name: 'Recent Passport-size Photograph',
      description: 'Formal color headshot for corporate ID badge',
      required: true,
      acceptedFormats: ['.jpg', '.jpeg', '.png'],
      maxSizeMb: 3,
    },
    {
      code: 'CANCELLED_CHEQUE',
      name: 'Cancelled Cheque or Bank Passbook Front Page',
      description: 'Proof of bank account holder name and IFSC code',
      required: true,
      acceptedFormats: ['.pdf', '.jpg', '.jpeg', '.png'],
      maxSizeMb: 5,
    },
  ],
  defaultChecklist: [
    {
      id: 'chk_it_laptop',
      title: 'IT Hardware & Laptop Provisioning',
      description: 'Allocate developer laptop, power adapter, and security peripheral package.',
      assigneeRole: 'IT',
      isMandatory: true,
      dueDateOffsetDays: -3,
    },
    {
      id: 'chk_it_email',
      title: 'Corporate Email & Identity Setup',
      description: 'Generate @tasknera.com Google Workspace email, Slack workspace access, and VPN credentials.',
      assigneeRole: 'IT',
      isMandatory: true,
      dueDateOffsetDays: -2,
    },
    {
      id: 'chk_hr_welcome',
      title: 'HR Welcome Call & Day 1 Induction',
      description: 'Schedule corporate induction briefing, assign buddy, and share first-week calendar.',
      assigneeRole: 'HR',
      isMandatory: true,
      dueDateOffsetDays: -1,
    },
    {
      id: 'chk_facilities_id',
      title: 'Employee ID Card & Access Badge Issuance',
      description: 'Print smart RFID access badge and register bio-attendance profile.',
      assigneeRole: 'FACILITIES',
      isMandatory: true,
      dueDateOffsetDays: 0,
    },
    {
      id: 'chk_mgr_intro',
      title: 'Hiring Manager 1-on-1 & Team Introduction',
      description: 'Host team welcome standup, review initial 30-day goals and project ownership.',
      assigneeRole: 'MANAGER',
      isMandatory: true,
      dueDateOffsetDays: 0,
    },
    {
      id: 'chk_hr_statutory',
      title: 'Statutory Benefits & PF/ESI Registration',
      description: 'Complete EPFO UAN linking, group medical cover enrollment, and gratuity nomination.',
      assigneeRole: 'HR',
      isMandatory: true,
      dueDateOffsetDays: 5,
    },
    {
      id: 'chk_emp_policies',
      title: 'Policy Signoff & Compliance Training Completed',
      description: 'Candidate reviews and electronically acknowledges all 19 company governance policies.',
      assigneeRole: 'EMPLOYEE',
      isMandatory: true,
      dueDateOffsetDays: 7,
    },
  ],
  updatedAt: new Date().toISOString(),
  updatedBy: 'usr_sakshi_1048',
};
