import React, { useState, useEffect } from 'react';
import {
  Sparkles,
  Wand2,
  Gift,
  TrendingUp,
  ShieldAlert,
  Check,
  Plus,
  RefreshCw,
} from 'lucide-react';
import { offerService } from '../../../services/offerService.js';
import { AiPerkSuggestion, OfferClauseItem } from '../../../types/offer.js';

interface Step8AiAssistanceProps {
  roleTitle: string;
  department: string;
  onAddClause: (clause: OfferClauseItem) => void;
  onAddBenefit: (benefitText: string) => void;
}

export const Step8AiAssistance: React.FC<Step8AiAssistanceProps> = ({
  roleTitle,
  department,
  onAddClause,
  onAddBenefit,
}) => {
  const [perks, setPerks] = useState<AiPerkSuggestion[]>([]);
  const [loadingPerks, setLoadingPerks] = useState(true);
  const [acceptedPerkIds, setAcceptedPerkIds] = useState<Record<string, boolean>>({});

  // Clause generator state
  const [clauseType, setClauseType] = useState('Remote Work Flexibility');
  const [clauseInstruction, setClauseInstruction] = useState('Draft an ergonomic home office and equipment stipend clause');
  const [generatingClause, setGeneratingClause] = useState(false);
  const [generatedClause, setGeneratedClause] = useState<OfferClauseItem | null>(null);

  useEffect(() => {
    loadPerks();
  }, [roleTitle, department]);

  const loadPerks = async () => {
    setLoadingPerks(true);
    try {
      const data = await offerService.getAiSuggestions(roleTitle, department);
      setPerks(data);
    } finally {
      setLoadingPerks(false);
    }
  };

  const handleAcceptPerk = (perk: AiPerkSuggestion) => {
    setAcceptedPerkIds((prev) => ({ ...prev, [perk.id]: true }));
    onAddBenefit(`${perk.title}: ${perk.suggestedWording}`);
  };

  const handleGenerateCustomClause = async () => {
    setGeneratingClause(true);
    try {
      const result = await offerService.generateClause(clauseType, clauseInstruction);
      setGeneratedClause(result);
    } finally {
      setGeneratingClause(false);
    }
  };

  const handleInsertGeneratedClause = () => {
    if (generatedClause) {
      onAddClause(generatedClause);
      setGeneratedClause(null);
    }
  };

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 20 }}>
      <div>
        <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
          <span
            style={{
              width: 28,
              height: 28,
              borderRadius: '50%',
              background: 'var(--primary)',
              color: '#fff',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              fontWeight: 800,
              fontSize: '0.875rem',
            }}
          >
            8
          </span>
          <h3 style={{ fontSize: '1.25rem', fontWeight: 800 }}>AI Offer Copilot & Advisory Intelligence</h3>
        </div>
        <p style={{ color: 'var(--text-muted)', fontSize: '0.875rem', marginTop: 4, marginLeft: 38 }}>
          Enhance offer competitiveness with tailored role perks, benchmark compensation checks, and clause wording generation.
        </p>
      </div>

      {/* Mandatory AI Guardrail Banner */}
      <div
        className="glass-panel"
        style={{
          padding: '14px 20px',
          background: 'rgba(168, 85, 247, 0.08)',
          border: '1px solid var(--ai-border)',
          display: 'flex',
          alignItems: 'center',
          gap: 12,
        }}
      >
        <ShieldAlert size={20} color="#c084fc" style={{ flexShrink: 0 }} />
        <div style={{ fontSize: '0.8125rem', color: '#f8fafc' }}>
          <strong>STRICT AI GUARDRAIL ACTIVE:</strong> All suggestions generated by AI Copilot are non-binding and advisory only. Sensitive legal commitments, binding compensation numbers, and policy thresholds require human HR confirmation before issuance.
        </div>
      </div>

      {/* Market Benchmark Insight */}
      <div
        className="glass-panel"
        style={{
          padding: 20,
          background: 'var(--bg-tertiary)',
          display: 'flex',
          flexDirection: 'column',
          gap: 12,
        }}
      >
        <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
          <TrendingUp size={18} color="var(--success)" />
          <h4 style={{ fontSize: '1rem', fontWeight: 700 }}>Real-Time Market Compensation Benchmark</h4>
        </div>

        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(140px, 1fr))', gap: 12 }}>
          <div style={{ padding: '10px 14px', borderRadius: 'var(--radius-md)', background: 'var(--bg-primary)' }}>
            <div style={{ fontSize: '0.6875rem', color: 'var(--text-dim)' }}>25TH PERCENTILE</div>
            <div style={{ fontSize: '1.05rem', fontWeight: 700, color: '#fff' }}>$142,000 USD</div>
          </div>
          <div style={{ padding: '10px 14px', borderRadius: 'var(--radius-md)', background: 'var(--bg-primary)' }}>
            <div style={{ fontSize: '0.6875rem', color: 'var(--text-dim)' }}>50TH (MEDIAN)</div>
            <div style={{ fontSize: '1.05rem', fontWeight: 700, color: '#fff' }}>$158,000 USD</div>
          </div>
          <div style={{ padding: '10px 14px', borderRadius: 'var(--radius-md)', background: 'rgba(16, 185, 129, 0.1)', border: '1px solid rgba(16, 185, 129, 0.3)' }}>
            <div style={{ fontSize: '0.6875rem', color: '#34d399', fontWeight: 700 }}>CURRENT OFFER (75TH)</div>
            <div style={{ fontSize: '1.05rem', fontWeight: 800, color: '#34d399' }}>$165,000 USD</div>
          </div>
          <div style={{ padding: '10px 14px', borderRadius: 'var(--radius-md)', background: 'var(--bg-primary)' }}>
            <div style={{ fontSize: '0.6875rem', color: 'var(--text-dim)' }}>90TH PERCENTILE</div>
            <div style={{ fontSize: '1.05rem', fontWeight: 700, color: '#fff' }}>$192,000 USD</div>
          </div>
        </div>
      </div>

      {/* Role Perks Recommendations */}
      <div
        className="glass-panel"
        style={{
          padding: 20,
          display: 'flex',
          flexDirection: 'column',
          gap: 16,
        }}
      >
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
            <Gift size={18} color="var(--primary)" />
            <h4 style={{ fontSize: '1rem', fontWeight: 700 }}>Tailored Role Perks for {roleTitle || 'Position'}</h4>
          </div>
          <button
            type="button"
            className="btn btn-ghost"
            onClick={loadPerks}
            disabled={loadingPerks}
            style={{ fontSize: '0.75rem', padding: '4px 8px' }}
          >
            <RefreshCw size={13} className={loadingPerks ? 'spinner' : ''} />
            <span>Regenerate</span>
          </button>
        </div>

        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: 14 }}>
          {perks.map((perk) => {
            const isAccepted = !!acceptedPerkIds[perk.id];

            return (
              <div
                key={perk.id}
                className="glass-panel"
                style={{
                  padding: 16,
                  display: 'flex',
                  flexDirection: 'column',
                  justifyContent: 'space-between',
                  gap: 12,
                  background: isAccepted ? 'rgba(16, 185, 129, 0.05)' : 'var(--bg-tertiary)',
                  border: isAccepted ? '1px solid var(--hr-border)' : '1px solid var(--border-subtle)',
                }}
              >
                <div>
                  <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 4 }}>
                    <span className="ai-badge" style={{ fontSize: '0.625rem', padding: '1px 6px' }}>
                      {perk.category}
                    </span>
                    {isAccepted && (
                      <span style={{ fontSize: '0.6875rem', color: 'var(--success)', fontWeight: 700, display: 'flex', alignItems: 'center', gap: 4 }}>
                        <Check size={12} />
                        <span>Included in Offer</span>
                      </span>
                    )}
                  </div>
                  <strong style={{ fontSize: '0.875rem', color: '#fff' }}>{perk.title}</strong>
                  <p style={{ fontSize: '0.75rem', color: 'var(--text-muted)', marginTop: 4, lineHeight: 1.4 }}>
                    {perk.suggestedWording}
                  </p>
                </div>

                <button
                  type="button"
                  className={isAccepted ? 'btn btn-ghost' : 'btn btn-secondary'}
                  disabled={isAccepted}
                  onClick={() => handleAcceptPerk(perk)}
                  style={{ fontSize: '0.75rem', padding: '6px 12px' }}
                >
                  {isAccepted ? 'Added to Benefits' : '+ Add Perk to Offer'}
                </button>
              </div>
            );
          })}
        </div>
      </div>

      {/* AI Clause Drafter Tool */}
      <div
        className="glass-panel"
        style={{
          padding: 20,
          display: 'flex',
          flexDirection: 'column',
          gap: 16,
          background: 'var(--bg-tertiary)',
        }}
      >
        <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
          <Wand2 size={18} color="#c084fc" />
          <h4 style={{ fontSize: '1rem', fontWeight: 700 }}>Custom Clause AI Drafter</h4>
        </div>

        <div style={{ display: 'grid', gridTemplateColumns: '1fr 2fr', gap: 12 }}>
          <div>
            <label className="form-label">Clause Subject</label>
            <input
              type="text"
              className="form-input"
              value={clauseType}
              onChange={(e) => setClauseType(e.target.value)}
              placeholder="e.g. Remote Flexibility"
            />
          </div>
          <div>
            <label className="form-label">Drafting Guidance</label>
            <div style={{ display: 'flex', gap: 8 }}>
              <input
                type="text"
                className="form-input"
                value={clauseInstruction}
                onChange={(e) => setClauseInstruction(e.target.value)}
                placeholder="e.g. Include equipment reimbursement policy"
              />
              <button
                type="button"
                className="btn btn-ai"
                onClick={handleGenerateCustomClause}
                disabled={generatingClause || !clauseInstruction.trim()}
                style={{ fontSize: '0.8125rem', whiteSpace: 'nowrap' }}
              >
                <Sparkles size={14} />
                <span>{generatingClause ? 'Drafting...' : 'Draft Clause'}</span>
              </button>
            </div>
          </div>
        </div>

        {/* Generated Clause Card */}
        {generatedClause && (
          <div
            className="glass-panel animate-fade-in"
            style={{
              padding: 16,
              background: 'rgba(168, 85, 247, 0.05)',
              border: '1px solid var(--ai-border)',
              display: 'flex',
              flexDirection: 'column',
              gap: 12,
            }}
          >
            <div>
              <span className="ai-badge" style={{ fontSize: '0.6875rem' }}>AI Generated Clause</span>
              <h5 style={{ fontSize: '0.9375rem', fontWeight: 700, color: '#fff', marginTop: 4 }}>
                {generatedClause.title}
              </h5>
              <div
                style={{ fontSize: '0.8125rem', color: 'var(--text-main)', marginTop: 4, lineHeight: 1.5 }}
                dangerouslySetInnerHTML={{ __html: generatedClause.content }}
              />
            </div>

            <div style={{ display: 'flex', justifyContent: 'flex-end', gap: 8 }}>
              <button
                type="button"
                className="btn btn-ghost"
                onClick={() => setGeneratedClause(null)}
                style={{ fontSize: '0.75rem' }}
              >
                Discard
              </button>
              <button
                type="button"
                className="btn btn-primary"
                onClick={handleInsertGeneratedClause}
                style={{ fontSize: '0.75rem' }}
              >
                <Plus size={14} />
                <span>Insert into Contract Clauses</span>
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};
