import React, { useState, useEffect } from 'react';
import {
  Sparkles,
  Wand2,
  Gift,
  TrendingUp,
  ShieldAlert,
  Check,
  Plus,
  RefreshCw,
} from 'lucide-react';
import { offerService } from '../../../services/offerService.js';
import { AiPerkSuggestion, OfferClauseItem } from '../../../types/offer.js';

interface Step8AiAssistanceProps {
  roleTitle: string;
  department: string;
  onAddClause: (clause: OfferClauseItem) => void;
  onAddBenefit: (benefitText: string) => void;
}

export const Step8AiAssistance: React.FC<Step8AiAssistanceProps> = ({
  roleTitle,
  department,
  onAddClause,
  onAddBenefit,
}) => {
  const [perks, setPerks] = useState<AiPerkSuggestion[]>([]);
  const [loadingPerks, setLoadingPerks] = useState(true);
  const [acceptedPerkIds, setAcceptedPerkIds] = useState<Record<string, boolean>>({});

  // Clause generator state
  const [clauseType, setClauseType] = useState('Remote Work Flexibility');
  const [clauseInstruction, setClauseInstruction] = useState('Draft an ergonomic home office and equipment stipend clause');
  const [generatingClause, setGeneratingClause] = useState(false);
  const [generatedClause, setGeneratedClause] = useState<OfferClauseItem | null>(null);

  useEffect(() => {
    loadPerks();
  }, [roleTitle, department]);

  const loadPerks = async () => {
    setLoadingPerks(true);
    try {
      const data = await offerService.getAiSuggestions(roleTitle, department);
      setPerks(data);
    } finally {
      setLoadingPerks(false);
    }
  };

  const handleAcceptPerk = (perk: AiPerkSuggestion) => {
    setAcceptedPerkIds((prev) => ({ ...prev, [perk.id]: true }));
    onAddBenefit(`${perk.title}: ${perk.suggestedWording}`);
  };

  const handleGenerateCustomClause = async () => {
    setGeneratingClause(true);
    try {
      const result = await offerService.generateClause(clauseType, clauseInstruction);
      setGeneratedClause(result);
    } finally {
      setGeneratingClause(false);
    }
  };

  const handleInsertGeneratedClause = () => {
    if (generatedClause) {
      onAddClause(generatedClause);
      setGeneratedClause(null);
    }
  };

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 20 }}>
      <div>
        <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
          <span
            style={{
              width: 28,
              height: 28,
              borderRadius: '50%',
              background: 'var(--primary)',
              color: '#fff',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              fontWeight: 800,
              fontSize: '0.875rem',
            }}
          >
            8
          </span>
          <h3 style={{ fontSize: '1.25rem', fontWeight: 800, color: '#0f172a' }}>AI Offer Copilot & Advisory Intelligence</h3>
        </div>
        <p style={{ color: '#64748b', fontSize: '0.875rem', marginTop: 4, marginLeft: 38 }}>
          Enhance offer competitiveness with tailored role perks, benchmark compensation checks, and clause wording generation.
        </p>
      </div>

      {/* Mandatory AI Guardrail Banner */}
      <div
        style={{
          padding: '14px 20px',
          background: '#f5f3ff',
          border: '1px solid #ddd6fe',
          borderRadius: 10,
          display: 'flex',
          alignItems: 'center',
          gap: 12,
        }}
      >
        <ShieldAlert size={20} color="#7c3aed" style={{ flexShrink: 0 }} />
        <div style={{ fontSize: '0.8125rem', color: '#4c1d95' }}>
          <strong>STRICT AI GUARDRAIL ACTIVE:</strong> All suggestions generated by AI Copilot are non-binding and advisory only. Sensitive legal commitments, binding compensation numbers, and policy thresholds require human HR confirmation before issuance.
        </div>
      </div>

      {/* Market Benchmark Insight */}
      <div
        style={{
          padding: 20,
          background: '#ffffff',
          borderRadius: 12,
          border: '1px solid var(--border-medium)',
          boxShadow: 'var(--shadow-sm)',
          display: 'flex',
          flexDirection: 'column',
          gap: 12,
        }}
      >
        <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
          <TrendingUp size={18} color="#059669" />
          <h4 style={{ fontSize: '1rem', fontWeight: 700, color: '#0f172a' }}>Real-Time Market Compensation Benchmark</h4>
        </div>

        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(140px, 1fr))', gap: 12 }}>
          <div style={{ padding: '10px 14px', borderRadius: 'var(--radius-md)', background: '#f8fafc', border: '1px solid var(--border-subtle)' }}>
            <div style={{ fontSize: '0.6875rem', color: '#64748b', fontWeight: 600 }}>25TH PERCENTILE</div>
            <div style={{ fontSize: '1.05rem', fontWeight: 700, color: '#0f172a' }}>$142,000 USD</div>
          </div>
          <div style={{ padding: '10px 14px', borderRadius: 'var(--radius-md)', background: '#f8fafc', border: '1px solid var(--border-subtle)' }}>
            <div style={{ fontSize: '0.6875rem', color: '#64748b', fontWeight: 600 }}>50TH (MEDIAN)</div>
            <div style={{ fontSize: '1.05rem', fontWeight: 700, color: '#0f172a' }}>$158,000 USD</div>
          </div>
          <div style={{ padding: '10px 14px', borderRadius: 'var(--radius-md)', background: '#ecfdf5', border: '1px solid #a7f3d0' }}>
            <div style={{ fontSize: '0.6875rem', color: '#047857', fontWeight: 700 }}>CURRENT OFFER (75TH)</div>
            <div style={{ fontSize: '1.05rem', fontWeight: 800, color: '#059669' }}>$165,000 USD</div>
          </div>
          <div style={{ padding: '10px 14px', borderRadius: 'var(--radius-md)', background: '#f8fafc', border: '1px solid var(--border-subtle)' }}>
            <div style={{ fontSize: '0.6875rem', color: '#64748b', fontWeight: 600 }}>90TH PERCENTILE</div>
            <div style={{ fontSize: '1.05rem', fontWeight: 700, color: '#0f172a' }}>$192,000 USD</div>
          </div>
        </div>
      </div>

      {/* Role Perks Recommendations */}
      <div
        style={{
          padding: 20,
          background: '#ffffff',
          borderRadius: 12,
          border: '1px solid var(--border-medium)',
          boxShadow: 'var(--shadow-sm)',
          display: 'flex',
          flexDirection: 'column',
          gap: 16,
        }}
      >
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
            <Gift size={18} color="var(--primary)" />
            <h4 style={{ fontSize: '1rem', fontWeight: 700, color: '#0f172a' }}>Tailored Role Perks for {roleTitle || 'Position'}</h4>
          </div>
          <button
            type="button"
            className="btn btn-ghost"
            onClick={loadPerks}
            disabled={loadingPerks}
            style={{ fontSize: '0.75rem', padding: '4px 8px' }}
          >
            <RefreshCw size={13} className={loadingPerks ? 'spinner' : ''} />
            <span>Regenerate</span>
          </button>
        </div>

        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: 14 }}>
          {perks.map((perk) => {
            const isAccepted = !!acceptedPerkIds[perk.id];

            return (
              <div
                key={perk.id}
                style={{
                  padding: 16,
                  borderRadius: 10,
                  display: 'flex',
                  flexDirection: 'column',
                  justifyContent: 'space-between',
                  gap: 12,
                  background: isAccepted ? '#ecfdf5' : '#f8fafc',
                  border: isAccepted ? '1px solid #a7f3d0' : '1px solid var(--border-subtle)',
                  boxShadow: 'var(--shadow-sm)',
                }}
              >
                <div>
                  <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 4 }}>
                    <span className="ai-badge" style={{ fontSize: '0.625rem', padding: '1px 6px' }}>
                      {perk.category}
                    </span>
                    {isAccepted && (
                      <span style={{ fontSize: '0.6875rem', color: '#059669', fontWeight: 700, display: 'flex', alignItems: 'center', gap: 4 }}>
                        <Check size={12} />
                        <span>Included in Offer</span>
                      </span>
                    )}
                  </div>
                  <strong style={{ fontSize: '0.875rem', color: '#0f172a' }}>{perk.title}</strong>
                  <p style={{ fontSize: '0.75rem', color: '#64748b', marginTop: 4, lineHeight: 1.4 }}>
                    {perk.suggestedWording}
                  </p>
                </div>

                <button
                  type="button"
                  className={isAccepted ? 'btn btn-ghost' : 'btn btn-secondary'}
                  disabled={isAccepted}
                  onClick={() => handleAcceptPerk(perk)}
                  style={{ fontSize: '0.75rem', padding: '6px 12px' }}
                >
                  {isAccepted ? 'Added to Benefits' : '+ Add Perk to Offer'}
                </button>
              </div>
            );
          })}
        </div>
      </div>

      {/* AI Drafting Assistant (Offer Wording, Welcome Text, Job Description, General & Custom Clauses) */}
      <div
        style={{
          padding: 20,
          background: '#ffffff',
          borderRadius: 12,
          border: '1px solid var(--border-medium)',
          boxShadow: 'var(--shadow-sm)',
          display: 'flex',
          flexDirection: 'column',
          gap: 16,
        }}
      >
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
            <Wand2 size={18} color="#7c3aed" />
            <h4 style={{ fontSize: '1rem', fontWeight: 700, color: '#0f172a' }}>AI Drafter & Clause Assistant</h4>
          </div>
          <span className="ai-badge" style={{ fontSize: '0.6875rem' }}>
            HR Reviewed & Editable
          </span>
        </div>

        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(130px, 1fr))', gap: 8 }}>
          {[
            { id: 'professional_offer_wording', label: 'Offer Wording' },
            { id: 'welcome_intro_text', label: 'Welcome Note' },
            { id: 'job_description_wording', label: 'Job Description' },
            { id: 'general_clauses', label: 'General Clauses' },
            { id: 'custom_hr_clauses', label: 'Custom HR Clauses' },
          ].map((cat) => (
            <button
              key={cat.id}
              type="button"
              onClick={() => {
                setClauseType(cat.label);
                if (cat.id === 'welcome_intro_text') {
                  setClauseInstruction('Draft an enthusiastic welcoming message for senior leadership hire');
                } else if (cat.id === 'job_description_wording') {
                  setClauseInstruction(`Draft core architectural deliverables and responsibilities for ${roleTitle || 'this role'}`);
                } else if (cat.id === 'general_clauses') {
                  setClauseInstruction('Draft standard IP assignment and trade secrets confidentiality clause');
                } else if (cat.id === 'custom_hr_clauses') {
                  setClauseInstruction('Draft ergonomic workstation setup and hybrid stipend terms');
                } else {
                  setClauseInstruction(`Draft formal appointment offer letter body for ${roleTitle || 'position'}`);
                }
              }}
              className={`btn ${clauseType === cat.label ? 'btn-primary' : 'btn-secondary'}`}
              style={{ fontSize: '0.75rem', padding: '6px 10px' }}
            >
              {cat.label}
            </button>
          ))}
        </div>

        <div style={{ display: 'grid', gridTemplateColumns: '1fr 2fr', gap: 12 }}>
          <div>
            <label className="form-label">Category / Subject</label>
            <input
              type="text"
              className="form-input"
              value={clauseType}
              onChange={(e) => setClauseType(e.target.value)}
              placeholder="e.g. Remote Flexibility"
            />
          </div>
          <div>
            <label className="form-label">Drafting Guidance</label>
            <div style={{ display: 'flex', gap: 8 }}>
              <input
                type="text"
                className="form-input"
                value={clauseInstruction}
                onChange={(e) => setClauseInstruction(e.target.value)}
                placeholder="e.g. Include equipment reimbursement policy"
              />
              <button
                type="button"
                className="btn btn-ai"
                onClick={handleGenerateCustomClause}
                disabled={generatingClause || !clauseInstruction.trim()}
                style={{ fontSize: '0.8125rem', whiteSpace: 'nowrap' }}
              >
                <Sparkles size={14} />
                <span>{generatingClause ? 'Drafting...' : 'Generate Draft'}</span>
              </button>
            </div>
          </div>
        </div>

        {/* Generated Clause Card with In-Place Editing */}
        {generatedClause && (
          <div
            className="animate-fade-in"
            style={{
              padding: 16,
              borderRadius: 10,
              background: '#f5f3ff',
              border: '1px solid #ddd6fe',
              display: 'flex',
              flexDirection: 'column',
              gap: 12,
            }}
          >
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
              <span className="ai-badge" style={{ fontSize: '0.6875rem' }}>AI Generated Draft</span>
              <span style={{ fontSize: '0.75rem', color: '#64748b' }}>Advisory • HR Editable</span>
            </div>

            <div>
              <h5 style={{ fontSize: '0.9375rem', fontWeight: 700, color: '#0f172a', marginBottom: 6 }}>
                {generatedClause.title}
              </h5>
              <textarea
                className="form-input"
                rows={4}
                value={generatedClause.content.replace(/<[^>]*>/g, '')}
                onChange={(e) => setGeneratedClause({ ...generatedClause, content: e.target.value })}
                style={{ width: '100%', background: '#ffffff', color: '#0f172a', fontFamily: 'inherit', fontSize: '0.875rem', lineHeight: 1.6 }}
              />
            </div>

            <div style={{ display: 'flex', justifyContent: 'flex-end', gap: 8 }}>
              <button
                type="button"
                className="btn btn-ghost"
                onClick={() => setGeneratedClause(null)}
                style={{ fontSize: '0.75rem' }}
              >
                Reject / Discard
              </button>
              <button
                type="button"
                className="btn btn-primary"
                onClick={handleInsertGeneratedClause}
                style={{ fontSize: '0.75rem' }}
              >
                <Plus size={14} />
                <span>Accept & Insert into Contract</span>
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

